CREATE TABLE ip_address (
  ip_id       BIGSERIAL PRIMARY KEY,
  ip          TEXT NOT NULL UNIQUE
);

CREATE TABLE user_identity (
  user_id BIGSERIAL PRIMARY KEY,
  user_name        TEXT,
  pass             TEXT
);

CREATE TABLE http_method (
  method_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  method    TEXT NOT NULL UNIQUE
);

CREATE TABLE resource (
  resource_id  BIGSERIAL PRIMARY KEY,
  path         TEXT NOT NULL
);

CREATE TABLE http_status (
  status_id  SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code SMALLINT NOT NULL UNIQUE
);

CREATE TABLE user_agent (
  agent_id    BIGSERIAL PRIMARY KEY,
  agent_string TEXT NOT NULL UNIQUE,
  family      TEXT,
  os          TEXT
);

CREATE TABLE referrer (
  referrer_id  BIGSERIAL PRIMARY KEY,
  referrer_url TEXT NOT NULL UNIQUE
  );

CREATE TABLE block (
  block_id    TEXT PRIMARY KEY, -- keep original block id string (or hashed)
  size_bytes  BIGINT
);

CREATE TABLE data_type (
  type_id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_name TEXT NOT NULL UNIQUE
);

-- Core log tables
CREATE TABLE access_log (
  access_id        BIGSERIAL PRIMARY KEY,
  ts               TIMESTAMPTZ NOT NULL,
  ip_id            BIGINT NOT NULL REFERENCES ip_address(ip_id) ON DELETE RESTRICT,
  user_id          BIGINT REFERENCES user_identity(user_id) ON DELETE SET NULL,
  method_id        SMALLINT NOT NULL REFERENCES http_method(method_id) ON DELETE RESTRICT,
  resource_id      BIGINT NOT NULL REFERENCES resource(resource_id) ON DELETE RESTRICT,
  status_id        SMALLINT NOT NULL REFERENCES http_status(status_id) ON DELETE RESTRICT,
  response_size    BIGINT,
  referrer_id      BIGINT REFERENCES referrer(referrer_id) ON DELETE SET NULL,
  agent_id         BIGINT REFERENCES user_agent(agent_id) ON DELETE SET NULL
);

-- Indexes for access_log
CREATE INDEX idx_access_log_ts ON access_log (ts);
CREATE INDEX idx_access_log_ip ON access_log (ip_id);
CREATE INDEX idx_access_log_resource ON access_log (resource_id);
CREATE INDEX idx_access_log_status ON access_log (status_id);
CREATE INDEX idx_access_log_method ON access_log (method_id);

-- Data receiver log
CREATE TABLE data_receiver_log (
  dr_log_id BIGSERIAL PRIMARY KEY,
  ts        TIMESTAMPTZ NOT NULL,
  block_id  TEXT NOT NULL REFERENCES block(block_id) ON DELETE RESTRICT,
  src_ip_id BIGINT NOT NULL REFERENCES ip_address(ip_id) ON DELETE RESTRICT,
  dst_ip_id BIGINT NOT NULL REFERENCES ip_address(ip_id) ON DELETE RESTRICT,
  size_bytes BIGINT,
  type_id   SMALLINT REFERENCES data_type(type_id) ON DELETE SET NULL,
  CONSTRAINT dr_src_dst_diff CHECK (src_ip_id IS NULL OR dst_ip_id IS NULL OR src_ip_id <> dst_ip_id)
);

CREATE INDEX idx_dr_ts ON data_receiver_log (ts);
CREATE INDEX idx_dr_block ON data_receiver_log (block_id);
CREATE INDEX idx_dr_src_ip ON data_receiver_log (src_ip_id);
CREATE INDEX idx_dr_dst_ip ON data_receiver_log (dst_ip_id);
CREATE INDEX idx_dr_type ON data_receiver_log (type_id);

-- Namesystem events (event header) and mapping to multiple blocks
CREATE TABLE namesystem_event (
  ns_event_id BIGSERIAL PRIMARY KEY,
  ts          TIMESTAMPTZ NOT NULL,
  src_ip_id   BIGINT REFERENCES ip_address(ip_id) ON DELETE SET NULL,
  dst_ip_id   BIGINT REFERENCES ip_address(ip_id) ON DELETE SET NULL,
  type_id     SMALLINT REFERENCES data_type(type_id) ON DELETE SET NULL,
  size_bytes  BIGINT
);

CREATE INDEX idx_ns_ts ON namesystem_event (ts);
CREATE INDEX idx_ns_src_ip ON namesystem_event (src_ip_id);
CREATE INDEX idx_ns_dst_ip ON namesystem_event (dst_ip_id);
CREATE INDEX idx_ns_type ON namesystem_event (type_id);

CREATE TABLE ns_event_block (
  ns_event_id BIGINT NOT NULL REFERENCES namesystem_event(ns_event_id) ON DELETE CASCADE,
  block_id    TEXT NOT NULL REFERENCES block(block_id) ON DELETE RESTRICT,
  PRIMARY KEY (ns_event_id, block_id)
);

CREATE INDEX idx_ns_event_block_block ON ns_event_block (block_id);